/*
 * Class to store the Data Mover constants that are used in many classes
 * @author Ximena Lasserre
 * @since Apr 2015
 */
public with sharing class DataMoverConstants {

	public static final String PICKLIST_STRING = 'PICKLIST'; 
	public static final String BOOLEAN_STRING = 'BOOLEAN';
	public static final String NOT_APPLICABLE_STRING = 'N/A';
	public static final String REFERENCE_STRING = 'REFERENCE';	
}